name: Publish to AMO

on:
  push:
    paths:
      - './manifest.json'
    tags:
      - 'Release-*'
      - 'Hotfix-*'

jobs:
  publish-to-amo:
    name: Build and publish the extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
            node-version: '16'
          
      - name: npm install webext
        run: npm install
        
      - name: npm build webext
        run: npm run build

      - name: Sign the web-ext
        uses: issammani/sign-web-extension-action@master
        with:
          web-ext-source-dir: "./"
          web-ext-target-dir: "./releases"
          amo-api-key: ${{ secrets.AMO_API_KEY }}
          amo-api-secret: ${{ secrets.AMO_API_SECRET }}
          sign-listed: true
